/* eslint-disable react-refresh/only-export-components */

import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Location
    'location.flag': '🇳🇬',
    'location.city': 'Lagos',
    'location.country': 'Nigeria',
    'location.full': 'Lagos, Nigeria',
    'location.language': 'English',

    // Navigation
    'nav.home': 'Home',
    'nav.categories': 'Categories',
    'nav.podcast': 'Podcast',
    'nav.entertainment': 'Entertainment',
    'nav.latest': 'Latest',
    'nav.about': 'About',
    'nav.contact': 'Contact Us',
    'nav.training': 'Training',
    'nav.explore': 'Explore',
    'nav.company': 'Company',
    'nav.allDesigns': 'All Designs',
    'nav.brands': "Brands We've Shaped",
    'nav.desc.categories': 'Browse every design category',
    'nav.desc.training': 'Free courses, optional materials',
    'nav.desc.podcast': 'Kreativity=Intelligence+Fun',
    'nav.desc.entertainment': 'Videos, shows and creative fun',
    'nav.desc.allDesigns': 'Our full logo portfolio',
    'nav.desc.brands': 'Logos we created for clients',
    'nav.desc.pricing': 'Download packs for clean files',
    'nav.desc.home': 'Back to the start',
    'nav.desc.about': 'Our story and team',
    'nav.desc.contact': "Let's work together",
    'nav.quickJump': 'Quick jump',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.main': 'Main navigation',
    'nav.breadcrumb': 'Breadcrumb',
    'nav.language': 'Language',
    'search.short': 'Search...',
    'search.pages': 'Pages & sections',
    'search.designs': 'Designs',
    'search.courses': 'Courses',
    'search.brands': 'Brand logos',
    'search.resultsFor': 'Results for "{q}"',
    'search.noResults': 'No results for "{q}". Try another word or browse a section below.',
    'search.popular': 'Popular searches',
    'search.jumpTo': 'Jump to a section',
    'search.close': 'Close search',
    'footer.explore': 'Explore',
    'footer.company': 'Company',

    // Hero
    'hero.badge': 'Premium Graphic Design Marketplace',
    'hero.new': 'NEW',
    'hero.title1': 'Unleash Your',
    'hero.title2': 'Creative Potential',
    'hero.subtitle': 'Discover 15,000+ premium designs, templates, and creative assets. From church flyers to birthday invitations, we do it better than anyone else.',
    'hero.search': 'Search...',

    // Logo Portfolio
    'portfolio.badge': 'Our Work',
    'portfolio.title': 'Brands We\'ve Shaped',
    'portfolio.subtitle': 'Transforming visions into iconic brand identities. Explore our portfolio of logo designs crafted with precision and creativity.',
    'portfolio.cta': 'More',

    // Categories
    'categories.title': 'Popular Template Categories',
    'categories.subtitle': 'Browse our extensive collection of premium designs organized by category.',
    'categories.workers_day': 'Workers Day',
    'categories.womens_day': "Women's Day",
    'categories.wedding_invites': 'Wedding IVs',
    'categories.vector_illustrations': 'Vector Illustrations',
    'categories.valentines_day': "Valentine's Day",
    'categories.teachers_day': "Teacher's Day",
    'categories.posters': 'Posters',
    'categories.png': 'PNG',
    'categories.party_flyers': 'Party Flyers',
    'categories.nigeria': 'Nigeria',
    'categories.muslim': 'Muslim',
    'categories.music_covers': 'Music Covers',
    'categories.happy_new_year': 'Happy New Year',
    'categories.halloween': 'Halloween',
    'categories.fonts': 'Fonts',
    'categories.festivities': 'Festivities',
    'categories.fathers_day': "Father's Day",
    'categories.easter_design': 'Easter Design',
    'categories.church_flyers': 'Church Flyers',
    'categories.christmas': 'Christmas',
    'categories.cameroon': 'Cameroon',
    'categories.birthday_designs': 'Birthday Designs',
    'categories.african_celebrities': 'African Celebrities PNG',
    'categories.3d_pngs': '3D PNGs',

    // Training
    'training.title': 'Training & Workshops',
    'training.subtitle': 'Enhance your skills with our expert-led training programs and workshops.',
    'training.enroll': 'Enroll Now',
    'training.enrollAria': 'Enroll in {course}',
    'training.students': 'students',
    'training.weeks': 'Weeks',
    'training.customPrompt': 'Need custom training for your team?',
    'training.customCta': 'Contact Us',
    'training.course.1.desc': 'Learn to design and build your own custom typefaces from sketch to final digital font files.',
    'training.course.1.f1': 'Letterform Design',
    'training.course.1.f2': 'Vector Construction',
    'training.course.1.f3': 'Font Software',
    'training.course.1.f4': 'Export & Distribution',
    'training.course.2.desc': 'Develop professional logo design skills from concept development to final presentation for clients.',
    'training.course.2.f1': 'Concept Development',
    'training.course.2.f2': 'Sketching Techniques',
    'training.course.2.f3': 'Vector Execution',
    'training.course.2.f4': 'Client Presentation',
    'training.course.3.desc': 'Master the fundamental principles of graphic design including color theory, typography, layout, and composition.',
    'training.course.3.f1': 'Color Theory',
    'training.course.3.f2': 'Typography Basics',
    'training.course.3.f3': 'Layout Design',
    'training.course.3.f4': 'Composition Rules',
    'training.course.4.desc': 'Comprehensive training on creating complete brand identity systems for businesses and organizations.',
    'training.course.4.f1': 'Brand Strategy',
    'training.course.4.f2': 'Visual Systems',
    'training.course.4.f3': 'Brand Guidelines',
    'training.course.4.f4': 'Real Projects',

    // Enrollment
    'enroll.eyebrow': 'Confirm your enrollment',
    'enroll.close': 'Close enrollment',
    'enroll.inc.live': 'Live interactive training sessions',
    'enroll.inc.mentorship': 'Mentorship & personal feedback',
    'enroll.inc.materials': 'All study materials, templates & assets',

    // Downloads
    'download.cta': 'Download',
    'download.withCredit': 'Download · 1 credit',
    'download.again': 'Download again',
    'download.signin': 'Sign in to download',
    'download.preview': 'Download Preview',
    'download.processing': 'Preparing…',
    'download.watermarkNote': 'Watermarked — buy a pack for clean files',
    'download.signinNote': 'Sign in to use your download credits',
    'download.creditNote': 'Clean, full-resolution file · credits left: {count}',
    'download.ownedNote': 'You own this design — clean re-downloads are free',
    'download.toastFree': 'Downloaded with watermark. Buy a pack for clean files!',
    'download.toastClean': 'Clean download complete. Enjoy!',
    'download.creditsLeft': 'Credits left: {count}',
    'download.toastPreview': 'Preview downloaded — share it anywhere.',
    'download.toastError': "We couldn't prepare your download. Please check your connection and try again.",
    'download.signedIn': 'Signed in. You can now download designs.',

    // Checkout, payments, cart, free training
    'training.free': 'Free',
    'training.materialsOptional': 'Materials {price} (optional)',
    'enroll.free': 'FREE',
    'enroll.freeTitle': 'Course Enrollment',
    'enroll.freeBlurb': 'Register now and join the training sessions at no cost.',
    'enroll.namePlaceholder': 'Your full name',
    'enroll.emailPlaceholder': 'Your email address',
    'enroll.freeCta': 'Enroll for free',
    'enroll.err.name': 'Please enter your name.',
    'enroll.err.email': 'Please enter a valid email address.',
    'enroll.freeSubject': 'Free enrollment: {course}',
    'enroll.freeMessage': 'Hello Krown Creative Factory,\n\nI would like to enroll for free in the {course} training.\n\nName: {name}\nEmail: {email}\n\nThank you!',
    'enroll.materialsName': 'Course Materials, Assets & Templates',
    'enroll.materialsBlurb': 'Optional: keep the downloadable course pack.',
    'enroll.inc.assets': 'Downloadable assets',
    'enroll.inc.templates': 'Ready-to-use templates',
    'enroll.materialsCta': 'Get the materials — {price}',
    'enroll.materialsOptional': 'Optional — you can enroll for free without it.',
    'enroll.materialsReason': 'Downloadable materials, assets and templates for this course.',
    'enroll.doneEyebrow': 'Free enrollment',
    'enroll.doneTitle': 'Almost there — send the email',
    'enroll.doneBody': 'Your email app has opened with your registration. Send it to confirm your place; our team will reply with the session details.',
    'enroll.doneHint': 'If your email app didn\'t open, write to this address with your name and the course.',
    'enroll.copyEmail': 'Copy email address',
    'enroll.emailCopied': 'Email address copied',
    'enroll.done': 'Done',
    'checkout.materialsTitle': 'Course materials',
    'checkout.method': 'Payment method',
    'checkout.paystackDetail': 'Card, bank transfer, USSD · Naira (NGN) · Nigeria',
    'checkout.monetbilDetail': 'Mobile Money (MTN, Orange) · FCFA (XAF) · Cameroon',
    'checkout.comingSoon': 'Coming soon',
    'checkout.email': 'Email address',
    'checkout.emailHint': 'Your receipt is sent here. It is also your account email.',
    'checkout.pay': 'Pay {amount} with {gateway}',
    'checkout.redirecting': 'Opening {gateway}…',
    'checkout.secure': 'Secure payment. Credits are added only after the payment is confirmed.',
    'checkout.secureMaterials': 'Secure payment. Our team sends your materials after the payment is confirmed.',
    'checkout.err.bad_email': 'Please enter a valid email address.',
    'checkout.err.network': 'No connection. Check your internet and try again.',
    'checkout.err.gateway_not_configured': 'Online payment is not available right now. Please try again later or email info@krowncf.com.',
    'checkout.err.gateway_unreachable': 'The payment provider is not responding. Please try again in a moment.',
    'checkout.err.gateway_rejected': 'The payment provider declined the request. Please try again or choose another method.',
    'checkout.err.currency_unavailable': 'This payment method is not available for this item yet.',
    'checkout.err.unknown': 'Something went wrong. Please try again.',
    'pay.verifying': 'Confirming your payment…',
    'pay.verifyingBody': 'Please keep this page open.',
    'pay.success': 'Payment confirmed',
    'pay.successCredits': '{count} download credits have been added to your account.',
    'pay.successMaterials': 'Thank you! Our team will send your course materials, assets and templates to your email. For help, contact us below.',
    'pay.materialsSupport': 'WhatsApp support',
    'pay.cancelled': 'Payment cancelled',
    'pay.cancelledBody': 'No money was taken. You can try again whenever you like.',
    'pay.failed': 'Payment failed',
    'pay.failedBody': 'The payment was not completed and nothing was added to your account.',
    'pay.pending': 'Payment still processing',
    'pay.pendingBody': 'Mobile Money payments can take a minute. Check again shortly.',
    'pay.error': 'We couldn\'t confirm your payment',
    'pay.errorBody': 'Your connection may have dropped. Check again — if you were charged, it will be confirmed.',
    'pay.reference': 'Reference',
    'pay.checkAgain': 'Check again',
    'pay.tryAgain': 'Try again',
    'pay.continue': 'Continue',
    'pay.back': 'Back',
    'pay.help': 'Need help? Email',
    'cart.title': 'Your selection',
    'cart.count': '{count} designs',
    'cart.countOne': '1 design',
    'cart.empty': 'Your selection is empty',
    'cart.emptyHint': 'Add designs you like, then get credits to download them clean.',
    'cart.oneCredit': '1 credit',
    'cart.remove': 'Remove {name}',
    'cart.needed': 'You need {count} more credits for this selection.',
    'cart.covered': 'Your credits already cover this selection.',
    'cart.checkout': 'Checkout: {pack} — {price}',
    'cart.reason': 'Credits for your selection of {count} designs.',
    'share.preparing': 'Preparing the watermarked image…',
    'share.readyTap': 'Watermarked image ready.',
    'share.shareNow': 'Share now',

    // Credit packs
    'packs.title': 'Buy download credits',
    'packs.close': 'Close',
    'packs.reasonClean': 'Clean, watermark-free downloads use credits. Pick a pack — 1 credit = 1 design.',
    'packs.balance': 'Your credits: {count}',
    'packs.benefitClean': 'Clean, full-resolution files — no watermark',
    'packs.never': 'Credits never expire',
    'packs.allCategories': 'Use them on any design, in any category',
    'packs.buy': 'Buy pack',
    'packs.paymentHint': 'Pay securely with Paystack (Naira) or Monetbil (Mobile Money). Credits are added once payment is confirmed.',
    'packs.seePricing': 'See pricing',
    'packs.later': 'Maybe later',
    'packs.stripTitle': 'Get clean files with credit packs',
    'pricing.badge': 'Pricing',
    'pricing.title': 'Simple pack pricing',
    'pricing.subtitle': 'No subscriptions. Buy a pack of download credits and use them whenever you like — 1 credit = 1 clean design.',
    'pricing.previewFree': 'Watermarked previews are always free',
    'pricing.credits': '{count} download credits',
    'pricing.creditOne': '1 download credit',
    'nav.pricing': 'Pricing',

    // Account
    'account.title': 'My account',
    'account.signedOut': 'Sign in to see your credits and downloads.',
    'account.signIn': 'Sign in',
    'account.credits': 'Download credits',
    'account.buyMore': 'Buy credits',
    'account.history': 'Download history',
    'account.noDownloads': 'No downloads yet.',
    'account.browse': 'Browse designs',
    'account.watermarked': 'Watermarked',
    'account.clean': 'Clean',
    'account.owned': '{count} designs owned — re-download them free',
    'account.purchases': 'Pack purchases',
    'account.signOut': 'Sign out',
    'account.linkAria': 'My account · credits: {count}',

    // WhatsApp sharing
    'share.button': 'Share on WhatsApp',
    'share.cardAria': 'Share {title} on WhatsApp',
    'share.subtitle': 'Every share carries the Krown Creative Factory brand.',
    'share.contact': 'Share to a contact or group',
    'share.contactHintWeb': 'Opens WhatsApp with the message and link',
    'share.status': 'Share to WhatsApp Status',
    'share.statusHintWeb': 'Saves the watermarked preview and copies the caption',
    'share.copy': 'Copy Link',
    'share.copyHint': 'For Instagram, Facebook, X and more',
    'share.quotaNote': 'Sharing never uses your credits.',
    'share.toastShared': 'Shared! Thanks for spreading the word 🔥',
    'share.toastCopied': 'Link copied!',
    'share.toastStatusWeb': 'Preview saved and caption copied. Open WhatsApp → Status to post it.',
    'share.toastError': "Couldn't share right now. Please try again.",
    'share.count': '{count} shares from you',
    'share.countOne': '1 share from you',
    'share.close': 'Close sharing',

    // Install (PWA)
    'pwa.title': 'Install Krown Creative Factory',
    'pwa.subtitle': 'Add the app to your home screen: faster, full-screen, and available offline.',
    'pwa.install': 'Install',
    'pwa.perkFast': 'Faster',
    'pwa.perkFull': 'Full-screen',
    'pwa.perkOffline': 'Works offline',
    'pwa.notNow': 'Not now',
    'pwa.iosStep1': 'Tap the Share button',
    'pwa.iosStep2': 'Choose “Add to Home Screen”',
    'pwa.gotIt': 'Got it',
    'pwa.installed': 'Krown Creative Factory is installed 🎉',
    'pwa.close': 'Close install prompt',

    // Podcasts
    'podcasts.title': 'Latest Podcasts',
    'podcasts.subtitle': 'Tune in to our podcast series featuring industry insights and creative discussions.',
    'podcasts.showName': 'Kreativity=Intelligence+Fun',
    'podcasts.description': 'Kreativity=Intelligence+Fun is a podcast that gives designers an avenue to learn and get access to knowledge that would naturally take them years of working experience to have. Tips, Advice, Guidance, and Historical views of Graphics Design.',
    'podcasts.tagline': 'Kreativity=Intelligence+Fun',
    'podcasts.episodes': 'Episodes',
    'podcasts.listeners': 'Listeners',
    'podcasts.weekly': 'Weekly',
    'podcasts.newEpisodes': 'New Episodes',
    'podcasts.listenOn': 'Listen & watch',
    'podcasts.spotify': 'Listen on Spotify',
    'podcasts.youtube': 'Watch on YouTube',

    // Entertainment
    'entertainment.title': 'ENTERTAINMENT',
    'entertainment.subtitle': 'Discover music from our talented artists and creators. Stream on your favorite platforms.',
    'entertainment.viewAll': 'View All Releases',

    // Events
    'events.title': 'Events',
    'events.subtitle': 'Join us at our upcoming events, workshops, and exhibitions.',

    // Footer
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.subtitle': 'Subscribe to our newsletter for the latest designs, exclusive offers, and creative tips.',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.newsletter.subscribed': 'Subscribed!',
    'footer.brand.description': 'Nigeria\'s premier graphic design marketplace. Premium designs for creative professionals.',
    'footer.quickLinks': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.ourOffice': 'Our Office',
    'footer.copyright': '© 2026 Krown Creative Factory. All rights reserved.',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact Us',

    // Contact
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Have a question or want to work together? We\'d love to hear from you.',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message Sent!',
    'contact.direct': 'Get In Touch Directly',
    'contact.ourOffice': 'Our Office',
    'contact.viewMap': 'View on Map',
    'contact.chat.greeting': 'Hi! How can we help you today?',
    'contact.chat.placeholder': 'Type your message...',
    'contact.chat.send': 'Send',

    // About
    'about.title': 'About Us',
    'about.heading': 'We Are',
    'about.intro': 'Founded with a vision to revolutionize the graphic design industry, Krown Creative Factory has grown to become Africa\'s premier destination for culturally suited design assets.',
    'about.description': 'We blend African cultural heritage with modern design aesthetics to create unique, impactful visual experiences that resonate with audiences worldwide.',
    'about.cta': 'Start Your Project',
    'about.badge1': 'Creative',
    'about.badge1Sub': 'Excellence',
    'about.badge2': 'Award',
    'about.badge2Sub': 'Winning',
    'about.team': 'Meet Our',
    'about.teamSub': 'Creative Team',
    'about.teamDesc': 'The talented minds behind Krown Creative Factory',
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'The creative minds behind Krown Creative Factory',
    'about.founder': 'Founder',
    'about.team.founder': 'Founder & Creative Director',
    'about.team.co_founder': 'Co-Founder & Tech Lead',
    'about.subtitle': 'Learn more about our journey and mission.',
  },
  fr: {
    // Location
    'location.flag': '🇨🇲',
    'location.city': 'Yaoundé',
    'location.country': 'Cameroun',
    'location.full': 'Yaoundé, Cameroun',
    'location.language': 'Français',

    // Navigation
    'nav.home': 'Accueil',
    'nav.categories': 'Catégories',
    'nav.podcast': 'Podcast',
    'nav.entertainment': 'Divertissement',
    'nav.latest': 'Derniers',
    'nav.about': 'À Propos',
    'nav.contact': 'Contactez-Nous',
    'nav.training': 'Formation',
    'nav.explore': 'Explorer',
    'nav.company': 'Entreprise',
    'nav.allDesigns': 'Tous les Designs',
    'nav.brands': 'Marques Façonnées',
    'nav.desc.categories': 'Parcourez toutes les catégories',
    'nav.desc.training': 'Cours gratuits, supports en option',
    'nav.desc.podcast': 'Kreativity=Intelligence+Fun',
    'nav.desc.entertainment': 'Vidéos, émissions et fun créatif',
    'nav.desc.allDesigns': 'Notre portfolio complet de logos',
    'nav.desc.brands': 'Logos créés pour nos clients',
    'nav.desc.pricing': 'Packs de fichiers sans filigrane',
    'nav.desc.home': 'Retour au début',
    'nav.desc.about': 'Notre histoire et notre équipe',
    'nav.desc.contact': 'Travaillons ensemble',
    'nav.quickJump': 'Accès rapide',
    'nav.openMenu': 'Ouvrir le menu',
    'nav.closeMenu': 'Fermer le menu',
    'nav.main': 'Navigation principale',
    'nav.breadcrumb': "Fil d'Ariane",
    'nav.language': 'Langue',
    'search.short': 'Rechercher...',
    'search.pages': 'Pages et sections',
    'search.designs': 'Designs',
    'search.courses': 'Formations',
    'search.brands': 'Logos de marques',
    'search.resultsFor': 'Résultats pour « {q} »',
    'search.noResults': 'Aucun résultat pour « {q} ». Essayez un autre mot ou explorez une section ci-dessous.',
    'search.popular': 'Recherches populaires',
    'search.jumpTo': 'Aller à une section',
    'search.close': 'Fermer la recherche',
    'footer.explore': 'Explorer',
    'footer.company': 'Entreprise',

    // Hero
    'hero.badge': 'Marketplace Premium de Design Graphique',
    'hero.new': 'NOUVEAU',
    'hero.title1': 'Libérez Votre',
    'hero.title2': 'Potentiel Créatif',
    'hero.subtitle': 'Découvrez plus de 15 000 designs premium, modèles et actifs créatifs. Des flyers d\'église aux invitations d\'anniversaire, nous le faisons mieux que quiconque.',
    'hero.search': 'Rechercher...',

    // Logo Portfolio
    'portfolio.badge': 'Notre Travail',
    'portfolio.title': 'Marques Que Nous Avons Façonnées',
    'portfolio.subtitle': 'Transformer les visions en identités de marque emblématiques. Explorez notre portfolio de conceptions de logos créés avec précision et créativité.',
    'portfolio.cta': 'Plus',

    // Categories
    'categories.title': 'Catégories de Modèles Populaires',
    'categories.subtitle': 'Parcourez notre vaste collection de designs premium organisés par catégorie.',
    'categories.workers_day': 'Journée des Travailleurs',
    'categories.womens_day': "Journée de la Femme",
    'categories.wedding_invites': 'Faire-part de Mariage',
    'categories.vector_illustrations': 'Illustrations Vectorielles',
    'categories.valentines_day': "Saint-Valentin",
    'categories.teachers_day': "Journée des Enseignants",
    'categories.posters': 'Affiches',
    'categories.png': 'PNG',
    'categories.party_flyers': 'Flyers de Fête',
    'categories.nigeria': 'Nigéria',
    'categories.muslim': 'Musulman',
    'categories.music_covers': 'Pochettes Musicales',
    'categories.happy_new_year': 'Bonne Année',
    'categories.halloween': 'Halloween',
    'categories.fonts': 'Polices',
    'categories.festivities': 'Festivités',
    'categories.fathers_day': "Fête des Pères",
    'categories.easter_design': 'Design de Pâques',
    'categories.church_flyers': 'Flyers d\'Église',
    'categories.christmas': 'Noël',
    'categories.cameroon': 'Cameroun',
    'categories.birthday_designs': 'Designs d\'Anniversaire',
    'categories.african_celebrities': 'Célébrités Africaines PNG',
    'categories.3d_pngs': 'PNG 3D',

    // Training
    'training.title': 'Formation et Ateliers',
    'training.subtitle': 'Améliorez vos compétences avec nos programmes de formation et ateliers dirigés par des experts.',
    'training.enroll': "S'inscrire",
    'training.enrollAria': "S'inscrire à {course}",
    'training.students': 'étudiants',
    'training.weeks': 'Semaines',
    'training.customPrompt': "Besoin d'une formation sur mesure pour votre équipe ?",
    'training.customCta': 'Contactez-nous',
    'training.course.1.desc': 'Apprenez à concevoir et créer vos propres polices, du croquis aux fichiers de police numériques finaux.',
    'training.course.1.f1': 'Dessin de lettres',
    'training.course.1.f2': 'Construction vectorielle',
    'training.course.1.f3': 'Logiciels de police',
    'training.course.1.f4': 'Export et distribution',
    'training.course.2.desc': 'Développez des compétences professionnelles en création de logos, du concept à la présentation finale au client.',
    'training.course.2.f1': 'Développement de concept',
    'training.course.2.f2': 'Techniques de croquis',
    'training.course.2.f3': 'Exécution vectorielle',
    'training.course.2.f4': 'Présentation client',
    'training.course.3.desc': 'Maîtrisez les principes fondamentaux du design graphique : théorie des couleurs, typographie, mise en page et composition.',
    'training.course.3.f1': 'Théorie des couleurs',
    'training.course.3.f2': 'Bases de la typographie',
    'training.course.3.f3': 'Mise en page',
    'training.course.3.f4': 'Règles de composition',
    'training.course.4.desc': "Formation complète sur la création de systèmes d'identité de marque pour les entreprises et organisations.",
    'training.course.4.f1': 'Stratégie de marque',
    'training.course.4.f2': 'Systèmes visuels',
    'training.course.4.f3': 'Charte graphique',
    'training.course.4.f4': 'Projets réels',

    // Enrollment
    'enroll.eyebrow': 'Confirmez votre inscription',
    'enroll.close': "Fermer l'inscription",
    'enroll.inc.live': 'Sessions de formation interactives en direct',
    'enroll.inc.mentorship': 'Mentorat et retours personnalisés',
    'enroll.inc.materials': "Tous les supports, modèles et ressources d'étude",

    // Downloads
    'download.cta': 'Télécharger',
    'download.withCredit': 'Télécharger · 1 crédit',
    'download.again': 'Télécharger à nouveau',
    'download.signin': 'Connectez-vous pour télécharger',
    'download.preview': "Télécharger l'Aperçu",
    'download.processing': 'Préparation…',
    'download.watermarkNote': 'Filigrane — achetez un pack pour des fichiers sans filigrane',
    'download.signinNote': 'Connectez-vous pour utiliser vos crédits',
    'download.creditNote': 'Fichier sans filigrane, pleine résolution · crédits restants : {count}',
    'download.ownedNote': 'Ce design vous appartient — re-téléchargements gratuits',
    'download.toastFree': 'Téléchargé avec filigrane. Achetez un pack pour des fichiers sans filigrane !',
    'download.toastClean': 'Téléchargement sans filigrane terminé. Profitez-en !',
    'download.creditsLeft': 'Crédits restants : {count}',
    'download.toastPreview': "Aperçu téléchargé — partagez-le où vous voulez.",
    'download.toastError': 'Impossible de préparer votre téléchargement. Vérifiez votre connexion et réessayez.',
    'download.signedIn': 'Connecté. Vous pouvez maintenant télécharger des designs.',

    // Checkout, payments, cart, free training
    'training.free': 'Gratuit',
    'training.materialsOptional': 'Supports {price} (optionnel)',
    'enroll.free': 'GRATUIT',
    'enroll.freeTitle': 'Inscription à la formation',
    'enroll.freeBlurb': 'Inscrivez-vous et participez gratuitement aux sessions de formation.',
    'enroll.namePlaceholder': 'Votre nom complet',
    'enroll.emailPlaceholder': 'Votre adresse e-mail',
    'enroll.freeCta': 'S\'inscrire gratuitement',
    'enroll.err.name': 'Veuillez saisir votre nom.',
    'enroll.err.email': 'Veuillez saisir une adresse e-mail valide.',
    'enroll.freeSubject': 'Inscription gratuite : {course}',
    'enroll.freeMessage': 'Bonjour Krown Creative Factory,\n\nJe souhaite m\'inscrire gratuitement à la formation {course}.\n\nNom : {name}\nE-mail : {email}\n\nMerci !',
    'enroll.materialsName': 'Supports, Ressources et Modèles du cours',
    'enroll.materialsBlurb': 'Optionnel : gardez le pack de cours téléchargeable.',
    'enroll.inc.assets': 'Ressources téléchargeables',
    'enroll.inc.templates': 'Modèles prêts à l’emploi',
    'enroll.materialsCta': 'Obtenir les supports — {price}',
    'enroll.materialsOptional': 'Optionnel — vous pouvez vous inscrire gratuitement sans.',
    'enroll.materialsReason': 'Supports, ressources et modèles téléchargeables pour cette formation.',
    'enroll.doneEyebrow': 'Inscription gratuite',
    'enroll.doneTitle': 'Presque fini — envoyez l\'e-mail',
    'enroll.doneBody': 'Votre application e-mail s\'est ouverte avec votre inscription. Envoyez-la pour confirmer votre place ; notre équipe vous répondra avec les détails des sessions.',
    'enroll.doneHint': 'Si votre application e-mail ne s\'est pas ouverte, écrivez à cette adresse avec votre nom et la formation.',
    'enroll.copyEmail': 'Copier l\'adresse e-mail',
    'enroll.emailCopied': 'Adresse e-mail copiée',
    'enroll.done': 'Terminé',
    'checkout.materialsTitle': 'Supports de cours',
    'checkout.method': 'Moyen de paiement',
    'checkout.paystackDetail': 'Carte, virement, USSD · Naira (NGN) · Nigeria',
    'checkout.monetbilDetail': 'Mobile Money (MTN, Orange) · FCFA (XAF) · Cameroun',
    'checkout.comingSoon': 'Bientôt disponible',
    'checkout.email': 'Adresse e-mail',
    'checkout.emailHint': 'Votre reçu est envoyé ici. C\'est aussi l\'e-mail de votre compte.',
    'checkout.pay': 'Payer {amount} avec {gateway}',
    'checkout.redirecting': 'Ouverture de {gateway}…',
    'checkout.secure': 'Paiement sécurisé. Les crédits sont ajoutés uniquement après confirmation du paiement.',
    'checkout.secureMaterials': 'Paiement sécurisé. Notre équipe envoie vos supports après confirmation du paiement.',
    'checkout.err.bad_email': 'Veuillez saisir une adresse e-mail valide.',
    'checkout.err.network': 'Pas de connexion. Vérifiez votre internet et réessayez.',
    'checkout.err.gateway_not_configured': 'Le paiement en ligne n\'est pas disponible pour le moment. Réessayez plus tard ou écrivez à info@krowncf.com.',
    'checkout.err.gateway_unreachable': 'Le prestataire de paiement ne répond pas. Réessayez dans un instant.',
    'checkout.err.gateway_rejected': 'Le prestataire de paiement a refusé la demande. Réessayez ou choisissez un autre moyen.',
    'checkout.err.currency_unavailable': 'Ce moyen de paiement n\'est pas encore disponible pour cet article.',
    'checkout.err.unknown': 'Une erreur s\'est produite. Veuillez réessayer.',
    'pay.verifying': 'Confirmation de votre paiement…',
    'pay.verifyingBody': 'Merci de garder cette page ouverte.',
    'pay.success': 'Paiement confirmé',
    'pay.successCredits': '{count} crédits de téléchargement ont été ajoutés à votre compte.',
    'pay.successMaterials': 'Merci ! Notre équipe vous enverra par e-mail vos supports, ressources et modèles de cours. Besoin d’aide ? Contactez-nous ci-dessous.',
    'pay.materialsSupport': 'Assistance WhatsApp',
    'pay.cancelled': 'Paiement annulé',
    'pay.cancelledBody': 'Aucun montant n\'a été débité. Vous pouvez réessayer quand vous voulez.',
    'pay.failed': 'Paiement échoué',
    'pay.failedBody': 'Le paiement n\'a pas abouti et rien n\'a été ajouté à votre compte.',
    'pay.pending': 'Paiement en cours de traitement',
    'pay.pendingBody': 'Les paiements Mobile Money peuvent prendre une minute. Vérifiez à nouveau dans un instant.',
    'pay.error': 'Impossible de confirmer votre paiement',
    'pay.errorBody': 'Votre connexion a peut-être été interrompue. Vérifiez à nouveau — si vous avez été débité, ce sera confirmé.',
    'pay.reference': 'Référence',
    'pay.checkAgain': 'Vérifier à nouveau',
    'pay.tryAgain': 'Réessayer',
    'pay.continue': 'Continuer',
    'pay.back': 'Retour',
    'pay.help': 'Besoin d\'aide ? Écrivez à',
    'cart.title': 'Votre sélection',
    'cart.count': '{count} designs',
    'cart.countOne': '1 design',
    'cart.empty': 'Votre sélection est vide',
    'cart.emptyHint': 'Ajoutez des designs, puis prenez des crédits pour les télécharger sans filigrane.',
    'cart.oneCredit': '1 crédit',
    'cart.remove': 'Retirer {name}',
    'cart.needed': 'Il vous faut {count} crédits de plus pour cette sélection.',
    'cart.covered': 'Vos crédits couvrent déjà cette sélection.',
    'cart.checkout': 'Payer : {pack} — {price}',
    'cart.reason': 'Crédits pour votre sélection de {count} designs.',
    'share.preparing': 'Préparation de l\'image avec filigrane…',
    'share.readyTap': 'Image avec filigrane prête.',
    'share.shareNow': 'Partager',

    // Credit packs
    'packs.title': 'Acheter des crédits',
    'packs.close': 'Fermer',
    'packs.reasonClean': 'Les téléchargements sans filigrane utilisent des crédits. Choisissez un pack — 1 crédit = 1 design.',
    'packs.balance': 'Vos crédits : {count}',
    'packs.benefitClean': 'Fichiers sans filigrane, en pleine résolution',
    'packs.never': "Les crédits n'expirent jamais",
    'packs.allCategories': "Utilisables sur n'importe quel design, dans toutes les catégories",
    'packs.buy': 'Acheter le pack',
    'packs.paymentHint': 'Payez en toute sécurité avec Paystack (Naira) ou Monetbil (Mobile Money). Les crédits sont ajoutés dès la confirmation du paiement.',
    'packs.seePricing': 'Voir les tarifs',
    'packs.later': 'Plus tard',
    'packs.stripTitle': 'Fichiers sans filigrane avec les packs de crédits',
    'pricing.badge': 'Tarifs',
    'pricing.title': 'Des packs simples',
    'pricing.subtitle': "Aucun abonnement. Achetez un pack de crédits et utilisez-les quand vous voulez — 1 crédit = 1 design sans filigrane.",
    'pricing.previewFree': 'Les aperçus avec filigrane sont toujours gratuits',
    'pricing.credits': '{count} crédits de téléchargement',
    'pricing.creditOne': '1 crédit de téléchargement',
    'nav.pricing': 'Tarifs',

    // Account
    'account.title': 'Mon compte',
    'account.signedOut': 'Connectez-vous pour voir vos crédits et téléchargements.',
    'account.signIn': 'Se connecter',
    'account.credits': 'Crédits de téléchargement',
    'account.buyMore': 'Acheter des crédits',
    'account.history': 'Historique des téléchargements',
    'account.noDownloads': 'Aucun téléchargement pour le moment.',
    'account.browse': 'Parcourir les designs',
    'account.watermarked': 'Avec filigrane',
    'account.clean': 'Sans filigrane',
    'account.owned': '{count} designs possédés — re-téléchargez-les gratuitement',
    'account.purchases': 'Achats de packs',
    'account.signOut': 'Se déconnecter',
    'account.linkAria': 'Mon compte · crédits : {count}',

    // WhatsApp sharing
    'share.button': 'Partager sur WhatsApp',
    'share.cardAria': 'Partager {title} sur WhatsApp',
    'share.subtitle': 'Chaque partage porte la marque Krown Creative Factory.',
    'share.contact': 'Partager à un contact ou un groupe',
    'share.contactHintWeb': 'Ouvre WhatsApp avec le message et le lien',
    'share.status': 'Partager sur le Statut WhatsApp',
    'share.statusHintWeb': "Enregistre l'aperçu avec filigrane et copie la légende",
    'share.copy': 'Copier le Lien',
    'share.copyHint': 'Pour Instagram, Facebook, X et plus',
    'share.quotaNote': "Le partage n'utilise jamais vos crédits.",
    'share.toastShared': 'Partagé ! Merci de faire passer le mot 🔥',
    'share.toastCopied': 'Lien copié !',
    'share.toastStatusWeb': 'Aperçu enregistré et légende copiée. Ouvrez WhatsApp → Statut pour le publier.',
    'share.toastError': 'Partage impossible pour le moment. Veuillez réessayer.',
    'share.count': '{count} partages de votre part',
    'share.countOne': '1 partage de votre part',
    'share.close': 'Fermer le partage',

    // Install (PWA)
    'pwa.title': 'Installer Krown Creative Factory',
    'pwa.subtitle': "Ajoutez l'app à votre écran d'accueil : plus rapide, plein écran et disponible hors ligne.",
    'pwa.install': 'Installer',
    'pwa.perkFast': 'Plus rapide',
    'pwa.perkFull': 'Plein écran',
    'pwa.perkOffline': 'Hors ligne',
    'pwa.notNow': 'Plus tard',
    'pwa.iosStep1': 'Touchez le bouton Partager',
    'pwa.iosStep2': '« Sur l’écran d’accueil »',
    'pwa.gotIt': 'Compris',
    'pwa.installed': 'Krown Creative Factory est installé 🎉',
    'pwa.close': "Fermer l'invitation d'installation",

    // Podcasts
    'podcasts.title': 'Derniers Podcasts',
    'podcasts.subtitle': 'Écoutez notre série de podcasts présentant des informations sur l\'industrie et des discussions créatives.',
    'podcasts.showName': 'Kreativity=Intelligence+Fun',
    'podcasts.description': "Kreativity=Intelligence+Fun est un podcast qui offre aux designers une occasion d'apprendre et d'accéder à des connaissances qui leur prendraient naturellement des années d'expérience professionnelle. Astuces, Conseils, Orientations et Regards Historiques sur le Design Graphique.",
    'podcasts.tagline': 'Kreativity=Intelligence+Fun',
    'podcasts.episodes': 'Épisodes',
    'podcasts.listeners': 'Auditeurs',
    'podcasts.weekly': 'Hebdo',
    'podcasts.newEpisodes': 'Nouveaux épisodes',
    'podcasts.listenOn': 'Écouter & regarder',
    'podcasts.spotify': 'Écouter sur Spotify',
    'podcasts.youtube': 'Regarder sur YouTube',

    // Entertainment
    'entertainment.title': 'DIVERTISSEMENT',
    'entertainment.subtitle': 'Découvrez la musique de nos artistes et créateurs talentueux. Diffusez sur vos plateformes préférées.',
    'entertainment.viewAll': 'Voir Toutes les Sorties',

    // Events
    'events.title': 'Événements',
    'events.subtitle': 'Rejoignez-nous à nos événements, ateliers et expositions à venir.',

    // Footer
    'footer.newsletter.title': 'Restez Informé',
    'footer.newsletter.subtitle': 'Abonnez-vous à notre newsletter pour les derniers designs, offres exclusives et conseils créatifs.',
    'footer.newsletter.placeholder': 'Entrez votre email',
    'footer.newsletter.subscribe': 'S\'abonner',
    'footer.newsletter.subscribed': 'Abonné!',
    'footer.brand.description': 'Le marketplace premium de design graphique du Nigeria. Designs premium pour les professionnels créatifs.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.categories': 'Catégories',
    'footer.ourOffice': 'Notre Bureau',
    'footer.copyright': '© 2026 Krown Creative Factory. Tous droits réservés.',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.contact': 'Contactez-Nous',

    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.subtitle': 'Avez-vous une question ou souhaitez-vous travailler ensemble? Nous aimerions avoir de vos nouvelles.',
    'contact.name': 'Nom Complet',
    'contact.email': 'Adresse Email',
    'contact.phone': 'Numéro de Téléphone',
    'contact.subject': 'Sujet',
    'contact.message': 'Votre Message',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'contact.sent': 'Message Envoyé!',
    'contact.direct': 'Contactez-Nous Directement',
    'contact.ourOffice': 'Notre Bureau',
    'contact.viewMap': 'Voir sur la Carte',
    'contact.chat.greeting': 'Salut! Comment pouvons-nous vous aider aujourd\'hui?',
    'contact.chat.placeholder': 'Tapez votre message...',
    'contact.chat.send': 'Envoyer',

    // About
    'about.title': 'À Propos de Nous',
    'about.heading': 'Nous Sommes',
    'about.intro': 'Fondé avec une vision de révolutionner l\'industrie du design graphique, Krown Creative Factory est devenu la destination premium d\'Afrique pour les actifs de design culturellement adaptés.',
    'about.description': 'Nous mélangeons le patrimoine culturel africain avec l\'esthétique de design moderne pour créer des expériences visuelles uniques et percutantes qui résonnent avec les publics du monde entier.',
    'about.cta': 'Commencer Votre Projet',
    'about.badge1': 'Excellence',
    'about.badge1Sub': 'Créative',
    'about.badge2': 'Prix',
    'about.badge2Sub': 'Gagnant',
    'about.team': 'Rencontrez Notre',
    'about.teamSub': 'Équipe Créative',
    'about.teamDesc': 'Les esprits talentueux derrière Krown Creative Factory',
    'about.team.title': 'Rencontrez Notre Équipe',
    'about.team.subtitle': 'Les esprits créatifs derrière Krown Creative Factory',
    'about.founder': 'Fondateur',
    'about.team.founder': 'Fondateur et Directeur Créatif',
    'about.team.co_founder': 'Co-Fondateur et Tech Lead',
    'about.subtitle': 'En savoir plus sur notre parcours et notre mission.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
